spring.application.name=mutual-fund-backend
spring.mvc.servlet.load-on-startup=1

spring.datasource.url=jdbc:postgresql://database-1.cpmua28oy5bs.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
gemini.api.key=${GEMINI_API_KEY}
fred.api.key=${FRED_API_KEY}
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
